"""One-off generator: for every distinct word-set family currently in
WORD_LISTS (grouped by frozenset(words), so e.g. morphology's 6 existing
grid-position variants all count as ONE family), adds 2 NEW random
grid-position permutations of that same word set -- more (distance
correlation, accuracy) sample points for gridness-vs-accuracy-scatter.py,
without introducing any new vocabulary.

Mirrors morphology_rand1/2/3's approach (plain random shuffles of the
same word multiset onto the grid, no special Latin-square structure) --
just extended to every family, not only morphology. New arrangements are
checked against every existing arrangement for that family (exact word
order) to avoid generating an accidental duplicate.

Naming: {base_key}_rand{N}, where base_key is the shortest existing key
in the family (e.g. "morphology", "text_numbers") and N continues from
whatever _randK suffixes already exist for that family (morphology
already has rand1-3, so its two new lists become rand4/rand5; every other
family starts at rand1/rand2).

This script only EDITS word_lists.py (pure Python, no GPU/model needed).
It does not run 01_reproduce.py -- that still needs to happen separately,
on a GPU machine, for each newly added key before gridness-vs-accuracy-
scatter.py can plot it.
"""
import re

from word_lists import WORD_LISTS

SEED = 42
WORD_LISTS_PATH = "word_lists.py"


def families():
    fams = {}
    for key, words in WORD_LISTS.items():
        fam = frozenset(words)
        fams.setdefault(fam, []).append(key)
    return fams


def next_rand_index(members):
    """Smallest N such that no existing member ends in _randN, continuing
    any existing numbering (morphology already has rand1-3)."""
    max_n = 0
    for m in members:
        match = re.search(r"_rand(\d+)$", m)
        if match:
            max_n = max(max_n, int(match.group(1)))
    return max_n + 1


def generate_new_arrangement(words, existing_arrangements, rng):
    words = list(words)
    for _ in range(1000):
        shuffled = words[:]
        rng.shuffle(shuffled)
        if tuple(shuffled) not in existing_arrangements:
            return shuffled
    raise RuntimeError("Could not find a non-duplicate permutation after 1000 tries.")


def format_word_list(words, side):
    """Match the repo's existing formatting: words wrapped `side` per line."""
    lines = []
    for i in range(0, len(words), side):
        row = words[i:i + side]
        lines.append("        " + ", ".join(f'"{w}"' for w in row) + ",")
    lines[-1] = lines[-1].rstrip(",")
    return "\n".join(lines)


def main():
    import random
    import math

    fams = families()
    new_entries = []  # (key, words, comment)

    for fam in sorted(fams.keys(), key=lambda f: min(fams[f], key=len)):
        members = fams[fam]
        base_key = min(members, key=len)
        words = WORD_LISTS[base_key]
        side = math.isqrt(len(words))
        if side * side != len(words):
            print(f"Skipping {base_key}: {len(words)} words is not a perfect square.")
            continue

        existing_arrangements = {tuple(WORD_LISTS[m]) for m in members}
        start_n = next_rand_index(members)

        rng = random.Random(f"{SEED}_{base_key}")
        for offset in range(2):
            n = start_n + offset
            new_words = generate_new_arrangement(words, existing_arrangements, rng)
            existing_arrangements.add(tuple(new_words))
            key = f"{base_key}_rand{n}"
            new_entries.append((key, new_words, side))
            print(f"Generated {key} ({len(members)} existing variants -> {len(members) + offset + 1})")

    with open(WORD_LISTS_PATH, "r") as f:
        content = f.read()

    assert content.rstrip().endswith("}")
    insert_point = content.rstrip().rfind("}")

    block_lines = [
        "",
        "    # ── Additional random grid-position permutations ─────────────────────",
        "    # Generated by generate_extra_grid_permutations.py: 2 new plain random",
        "    # shuffles per existing word-set family (same words, new grid layout),",
        "    # for more (distance correlation, accuracy) points on the gridness-vs-",
        "    # accuracy scatter. Requires 01_reproduce.py to be run for each new key",
        "    # (GPU) before it can be plotted.",
    ]
    for key, words, side in new_entries:
        block_lines.append(f'    "{key}": [')
        block_lines.append(format_word_list(words, side))
        block_lines.append("    ],")
        block_lines.append("")

    new_content = content[:insert_point] + "\n".join(block_lines) + "\n}\n"
    with open(WORD_LISTS_PATH, "w") as f:
        f.write(new_content)

    print(f"\nAdded {len(new_entries)} new word lists to {WORD_LISTS_PATH}.")


if __name__ == "__main__":
    main()
